### ISSUE TITLE
API Token

### ISSUE THREAD

**Issue by Ytrnfhsy** [Fus3n/code-former-ps#2]
I can't enter API Token. When selecting "Set Replicate API Token", nothing happens

**Comment by Fus3n** [comment]
![Untitled](https://github.com/Fus3n/code-former-ps/assets/52007265/307f3ce0-11a6-44c0-93b8-9bf331cb2c4f)

Try clicking the cogwheel icon in the sidebar

**Comment by Fus3n** [comment]
![tutorial1](https://github.com/Fus3n/code-former-ps/assets/52007265/43c8d26a-788a-4dda-8ad1-dc192e34848a)

Try clicking the cogwheel button in the sidebar menu, if you don't see the menu click on menu `Plugins > CodeFromerPS > CodeFromerPS` 

![Untitled2](https://github.com/Fus3n/code-former-ps/assets/52007265/45889feb-ee77-4756-942d-f4358390939f)

It will popup this, then you can set your API key

if you still don't see it try reinstalling the addon

**Comment by Ytrnfhsy** [comment]
Thank you very much for your answer and your work, but for some reason it still doesn't work for me. Even after reinstalling

**Comment by Ytrnfhsy** [comment]
I have CodeFormer installed locally, is there any way to connect it to this plugin?

**Comment by Fus3n** [comment]
> Thank you very much for your answer and your work, but for some reason it still doesn't work for me. Even after reinstalling

Then probably it's your Photoshop version, my addon wasn't built with old versions in mind so might cause issues you should update it if it is an older one 

> I have CodeFormer installed locally, is there any way to connect it to this plugin?

For now no, might be in the future.

**Comment by Ytrnfhsy** [comment]
I have Photoshop version 25.5.0. Maybe some Windows components are missing?

**Comment by Fus3n** [comment]
> I have Photoshop version 25.5.0. Maybe some Windows components are missing?

It was tested on Windows 10 and 11 on multiple devices so shouldn't have issues with that it could be Photoshop itself though as I personally had issues with handling addons in general with Photoshop where I had to reinstall Photoshop you try that. If it's not Photoshop I might have to look into the addon.

Also, you could try on photoshop 25.1.0 as it was the version I tested on, new versions shouldn't break the addon but give it a try

**Comment by Ytrnfhsy** [comment]
Installed version 25.1, now the API Token input window appears, but an error occurs when processing the image
![2024-03-07 14_05_14-](https://github.com/Fus3n/code-former-ps/assets/102771594/78ab5f42-e48f-47d5-8767-c0413aef8a1e)

**Comment by Fus3n** [comment]
Do you have the correct API Code? Make sure theres nothign else in front or at the end like http or anything like that, just the code
I tested it the addon doesn't seem to have an internal error. But not entirely sure

**Comment by Ytrnfhsy** [comment]
> Do you have the correct API Code? Make sure theres nothign else in front or at the end like http or anything like that, just the code I tested it the addon doesn't seem to have an internal error. But not entirely sure

API code or token?

**Comment by Ytrnfhsy** [comment]
![2024-03-21 18_50_29-Account settings – Replicate — Mozilla Firefox](https://github.com/Fus3n/code-former-ps/assets/102771594/8820c2a3-495e-410e-be05-34d42c1cca8e)
this is the replicate.com token API

**Comment by Fus3n** [comment]
I have updated the addon so the dialog issue doesn't happen along with some other stuff you can try to see if the new version works or not [https://github.com/Fus3n/code-former-ps/releases/tag/1.1.0](https://github.com/Fus3n/code-former-ps/releases/tag/1.1.0)

**Comment by Fus3n** [comment]
Closing as problem seem to be fixed and working on most devices

**Comment by oky5758** [comment]
how to install?

**Comment by Fus3n** [comment]
> how to install?

if you double click the cxx file it will prompt in creative cloud.
