### ISSUE TITLE
25.7.0 Beta Not showing Api Token Window

### ISSUE THREAD

**Issue by nizamonn** [Fus3n/code-former-ps#3]
25.7.0 Beta Not showing Api Token Window

**Comment by Fus3n** [comment]
Does it work on the normal versions? beta Photoshop itself might have bugs so it could not be the issue of the addon itself so updating for it won't be of any use, so if it works on the release version please use that.

**Comment by nizamonn** [comment]
I checked with latest normal version Photoshop same problem can you fix that

**Comment by nizamonn** [comment]
> Does it work on the normal versions? beta Photoshop itself might have bugs so it could not be the issue of the addon itself so updating for it won't be of any use, so if it works on the release version please use that.

25.6.0 My release version Same problem

**Comment by anubisthetyrant** [comment]
I have 25.6.0 Release version and I have the same problem. I am unable to set API Token

**Comment by Fus3n** [comment]
Sorry for all the suffering. I now have updated the latest release it contains the correct file and shows API token window,
Thank you for all the reports.
